// The one command for Stardust 3D models:   npm run assets:3d
//
//   1. regenerates tools/3d/hull-targets.json from the game's hull code (engine/hull.js);
//   2. runs Blender (tools/3d/export_ships.py) to export the ships from their read-only sources,
//      and (with --incoming) to convert drop-in files from tools/3d/incoming/;
//   3. rebuilds projects/Space-Shooter/art/3d/manifest.json: sizes, hashes, triangle and texture
//      counts, provenance, and the transform fields (rotation / scale / pivot / fit / offset).
//      Fields you set by hand (rotation, scale, offset, pivot, fit) survive a rebuild.
//
// Options:
//   --no-blender   only rebuild the manifest from the .glb files already in art/3d (fast; no Blender needed)
//   --incoming     also convert tools/3d/incoming/{ships,props}/*.glb  (what `npm run assets:3d:incoming` does)
//   --only a,b     export only these names
//   --sources DIR  where the read-only Blender sources live (or set STARDUST_ART_SOURCES)
//   --check        do not write; exit 1 if the manifest on disk is stale or any model is over budget
// Blender: set BLENDER to the executable, otherwise the usual Windows install paths are tried.
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { inspectGlb, sha256File } from './glb.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..', '..');
const art = path.join(repo, 'projects', 'Space-Shooter', 'art', '3d');
const manifestPath = path.join(art, 'manifest.json');
const reportPath = path.join(here, 'export-report.json');
const args = process.argv.slice(2);
const flag = (n) => args.includes(n);
const option = (n) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : undefined; };

export const BUDGETS = Object.freeze({
  shipBytes: 1_500_000,      // per ship .glb (decimal MB, so "1.5 MB" means exactly that)
  propBytes: 1_000_000,
  textureSide: 1024,         // longest texture side, px
  shipTriangles: 60_000,
  propTriangles: 30_000,
});
const SHIP_ORDER = ['default', 'courier', 'needle', 'manta', 'wisp'];
const PROP_ORDER = ['fuelStation', 'mine', 'asteroid', 'shard', 'sentry'];
const PROP_FIT = { fuelStation: { radius: 1 }, mine: { radius: 0.42 }, asteroid: { radius: 1 }, shard: { length: 0.95 }, sentry: { radius: 0.5 } };
const PROP_PIVOT = { fuelStation: 'bottom', sentry: 'bottom' };

function findBlender() {
  const candidates = [process.env.BLENDER];
  const root = 'C:/Program Files/Blender Foundation';
  if (existsSync(root)) for (const d of readdirSync(root).sort().reverse()) candidates.push(path.join(root, d, 'blender.exe'));
  candidates.push('/Applications/Blender.app/Contents/MacOS/Blender', 'blender');
  return candidates.find((c) => c && (c === 'blender' || existsSync(c)));
}

function run(cmd, cmdArgs, label) {
  console.log(`\n> ${label}`);
  const r = spawnSync(cmd, cmdArgs, { cwd: repo, stdio: 'inherit' });
  if (r.status !== 0) throw new Error(`${label} failed (exit ${r.status})`);
}

const readJson = (p, fallback) => { try { return JSON.parse(readFileSync(p, 'utf8')); } catch { return fallback; } };
const r4 = (v) => Math.round(v * 10000) / 10000;

/** Builds the manifest object from the .glb files on disk plus the previous manifest and the export report. */
export function buildManifest({ previous = {}, report = { models: [] }, artDir = art } = {}) {
  const manifest = {
    version: 1,
    units: previous.units || 'One unit is one sim cell. Models face +X (the sim\'s angle 0), up is +Y, origin at the hull centre.',
    note: 'GENERATED by tools/3d/build.mjs (npm run assets:3d). rotation / scale / offset / pivot / fit are yours to edit and survive a rebuild; everything else is measured.',
    budgets: BUDGETS,
    ships: {},
    props: {},
  };
  const reported = new Map((report.models || []).filter((m) => !m.error).map((m) => [`${m.kind}s/${m.name}`, m]));
  for (const [kind, orderList] of [['ships', SHIP_ORDER], ['props', PROP_ORDER]]) {
    const dir = path.join(artDir, kind);
    const files = existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith('.glb')).map((f) => f.slice(0, -4)) : [];
    const names = [...orderList.filter((n) => files.includes(n)), ...files.filter((n) => !orderList.includes(n)).sort()];
    for (const name of names) {
      const rel = `${kind}/${name}.glb`;
      const abs = path.join(artDir, rel);
      const info = inspectGlb(abs);
      const sha = sha256File(abs);
      const prev = previous[kind]?.[name] || {};
      const rep = reported.get(`${kind}/${name}`);
      const repFresh = rep && rep.sha256 === sha ? rep : null;
      const isShip = kind === 'ships';
      const entry = { file: rel };
      // Hand-editable transform: keep what is there, else the defaults for an exported/dropped file.
      entry.rotation = prev.rotation || [0, 0, 0];
      entry.scale = prev.scale ?? 1;
      entry.offset = prev.offset || [0, 0, 0];
      if (repFresh) {          // freshly exported: already centred and sized by the exporter
        entry.pivot = 'none';
        entry.fit = repFresh.hullTarget ? { radius: r4(repFresh.hullTarget.radius) } : repFresh.fit || {};
      } else {
        entry.pivot = prev.pivot || (isShip ? 'center' : PROP_PIVOT[name] || 'center');
        entry.fit = prev.fit || (isShip ? { radius: 0.6 } : PROP_FIT[name] || { radius: 0.5 });
      }
      if (repFresh?.hullTarget) {
        const h = repFresh.hullTarget;
        entry.hull = { build: h.build, radius: r4(h.radius), length: r4(h.length), width: r4(h.width), nose: r4(h.nose), tail: r4(h.tail), buildScale: h.buildScale };
        entry.hullFit = { radiusRatio: r4(repFresh.hullFit.radiusRatio), lengthRatio: r4(repFresh.hullFit.lengthRatio), widthRatio: r4(repFresh.hullFit.widthRatio) };
      } else if (prev.hull) { entry.hull = prev.hull; if (prev.hullFit && prev.sha256 === sha) entry.hullFit = prev.hullFit; }
      entry.bytes = info.bytes;
      entry.sha256 = sha;
      entry.triangles = Math.round(info.triangles);
      entry.vertices = info.vertices;
      entry.materials = info.materials;
      entry.textures = info.images.map((i) => ({ width: i.width, height: i.height, mime: i.mime, bytes: i.bytes }));
      entry.extensions = info.extensionsRequired;
      entry.size = info.bounds ? info.bounds.size.map(r4) : null;
      entry.footprintRadius = info.footprintRadius === null ? null : r4(info.footprintRadius);
      if (repFresh) {
        entry.provenance = {
          source: repFresh.source, sourceSha256: repFresh.sourceSha256, sourceBytes: repFresh.sourceBytes, sourceTriangles: repFresh.sourceTriangles,
          sourceObjects: repFresh.sourceObjects, note: repFresh.note, orientation: repFresh.orientation, postProcess: repFresh.postProcess,
          exporter: 'tools/3d/export_ships.py', blender: report.blender, exportedAt: report.generated,
        };
      } else if (prev.provenance && prev.sha256 === sha) entry.provenance = prev.provenance;
      else entry.provenance = { source: 'dropped into art/3d by hand', note: 'Not produced by tools/3d/export_ships.py; run `npm run assets:3d:incoming` to optimise a raw download.' };
      manifest[kind][name] = entry;
    }
  }
  // Aliases: ships.default stays an alias of the Courier (the standard ship) unless a real default file exists.
  const prevDefault = previous.ships?.default;
  if (!manifest.ships.default) {
    if (prevDefault?.alias && manifest.ships[prevDefault.alias]) manifest.ships.default = { alias: prevDefault.alias };
    else if (manifest.ships.courier) manifest.ships.default = { alias: 'courier' };
    else { const first = SHIP_ORDER.find((n) => manifest.ships[n]) || Object.keys(manifest.ships)[0]; if (first) manifest.ships.default = { alias: first }; }
    const ordered = {};
    for (const n of [...SHIP_ORDER, ...Object.keys(manifest.ships)]) if (manifest.ships[n] && !ordered[n]) ordered[n] = manifest.ships[n];
    manifest.ships = ordered;
  }
  return manifest;
}

/** Budget problems for a manifest as [message...] (empty = fine). */
export function budgetProblems(manifest) {
  const problems = [];
  for (const [kind, table] of Object.entries({ ship: manifest.ships, prop: manifest.props })) {
    for (const [name, e] of Object.entries(table)) {
      if (e.alias) continue;
      const maxBytes = kind === 'ship' ? BUDGETS.shipBytes : BUDGETS.propBytes, maxTris = kind === 'ship' ? BUDGETS.shipTriangles : BUDGETS.propTriangles;
      if (e.bytes > maxBytes) problems.push(`${kind} ${name}: ${(e.bytes / 1e6).toFixed(2)} MB is over the ${(maxBytes / 1e6).toFixed(1)} MB budget`);
      if (e.triangles > maxTris) problems.push(`${kind} ${name}: ${e.triangles} triangles is over the ${maxTris} budget`);
      for (const t of e.textures || []) if (Math.max(t.width || 0, t.height || 0) > BUDGETS.textureSide) problems.push(`${kind} ${name}: a ${t.width}x${t.height} texture is over ${BUDGETS.textureSide}px`);
    }
  }
  return problems;
}

async function main() {
  if (!flag('--no-blender') && !flag('--check')) {
    run(process.execPath, [path.join(here, 'hull-targets.mjs')], 'hull targets');
    const blender = findBlender();
    if (!blender) throw new Error('Blender not found. Install Blender 4.2+ or set BLENDER, or use --no-blender to only rebuild the manifest.');
    const py = ['-b', '--python', path.join(here, 'export_ships.py'), '--'];
    if (flag('--incoming')) py.push('--incoming');
    if (option('--only')) py.push('--only', option('--only'));
    // A ship you replaced with your own Meshy remake must not be overwritten by the old source: skip every name
    // that has a raw file in tools/3d/incoming, or whose manifest provenance says it came from there.
    const keep = new Set();
    const previous = readJson(manifestPath, {});
    for (const kind of ['ships', 'props']) {
      for (const [name, e] of Object.entries(previous[kind] || {})) if (/^tools\/3d\/incoming\//.test(e.provenance?.source || '')) keep.add(name);
      const dir = path.join(here, 'incoming', kind);
      if (existsSync(dir)) for (const f of readdirSync(dir)) if (/\.glb$/i.test(f)) keep.add(f.slice(0, -4));
    }
    if (keep.size) { py.push('--skip', [...keep].join(',')); console.log(`keeping owner remakes: ${[...keep].join(', ')}`); }
    if (option('--sources')) py.push('--sources', option('--sources'));
    const started = Date.now();
    run(blender, py, `Blender export (${blender})`);
    // Blender exits 0 even when the script dies, so insist on a fresh report with no failed model.
    const fresh = existsSync(reportPath) && statSync(reportPath).mtimeMs >= started - 1000;
    const failed = fresh ? (readJson(reportPath, { models: [] }).models || []).filter((m) => m.error) : [];
    if (!fresh) throw new Error('Blender did not write a new tools/3d/export-report.json: the export script failed (see the output above).');
    if (failed.length) throw new Error('export failed for: ' + failed.map((m) => `${m.name} (${m.error})`).join(', '));
  }
  const manifest = buildManifest({ previous: readJson(manifestPath, {}), report: readJson(reportPath, { models: [] }) });
  const text = JSON.stringify(manifest, null, 2) + '\n';
  const problems = budgetProblems(manifest);
  if (flag('--check')) {
    const stale = readFileSync(manifestPath, 'utf8') !== text;
    if (stale) console.error('manifest.json is out of date: run `npm run assets:3d:manifest`');
    for (const p of problems) console.error('over budget:', p);
    process.exit(stale || problems.length ? 1 : 0);
  }
  writeFileSync(manifestPath, text);
  console.log(`\nwrote ${path.relative(repo, manifestPath)}`);
  for (const [kind, table] of Object.entries({ ships: manifest.ships, props: manifest.props })) {
    for (const [name, e] of Object.entries(table)) console.log(`  ${kind}/${name}`.padEnd(24), e.alias ? `-> ${e.alias}` : `${(e.bytes / 1e6).toFixed(2)} MB  ${e.triangles} tris  ${e.textures.length} textures`);
  }
  for (const p of problems) console.warn('OVER BUDGET:', p);
  if (problems.length) process.exitCode = 1;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => { console.error(error.message || error); process.exit(1); });
}
