// Writes tools/3d/hull-targets.json: the game's own hull sizes, which the Blender
// exporter (export_ships.py) scales each ship model to. Read-only on the game code.
//   node tools/3d/hull-targets.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { PLAYER_HULL, hullForBuild } from '../../projects/Space-Shooter/engine/hull.js';
import { buildScale } from '../../projects/Space-Shooter/engine/shipStats.js';
import { SHIP_HULL_GEOMETRY } from '../../projects/Space-Shooter/engine/shipHulls.js';

const r = (v) => Math.round(v * 10000) / 10000;
function describe(hull, build) {
  let minX = Infinity, maxX = -Infinity;
  for (const [x] of hull.points) { minX = Math.min(minX, x); maxX = Math.max(maxX, x); }
  return {
    build,                       // null = the standard ship (no garage build)
    radius: r(hull.radius),      // farthest hull vertex from the origin, in sim cells
    halfSpan: r(hull.halfSpan),  // half the wingspan
    nose: r(hull.nose),          // reach forward
    tail: r(hull.tail),          // reach backward
    width: r(maxX - minX),
    length: r(hull.nose + hull.tail),
    buildScale: build ? buildScale(build) : 1,
  };
}

// Each exported ship maps to the garage build whose hull its sprite art defines.
const targets = {
  standard: describe(PLAYER_HULL, null),
  courier: describe(hullForBuild('courier:0-0-0-0'), 'courier:0-0-0-0'),
  needle: describe(hullForBuild('needle:0-0-0-0'), 'needle:0-0-0-0'),
  manta: describe(hullForBuild('manta:0-0-0-0'), 'manta:0-0-0-0'),
  wisp: describe(hullForBuild('wisp:0-0-0-0'), 'wisp:0-0-0-0'),
};
const out = {
  note: 'GENERATED by tools/3d/hull-targets.mjs from engine/hull.js and engine/shipStats.js. Ship-local frame: x = right, y = forward (nose); the 3D export is forward +X.',
  hullGeometry: SHIP_HULL_GEOMETRY,
  targets,
};
const file = fileURLToPath(new URL('./hull-targets.json', import.meta.url));
writeFileSync(file, JSON.stringify(out, null, 2) + '\n');
console.log('wrote', file);
for (const [k, v] of Object.entries(targets)) console.log(k.padEnd(8), JSON.stringify(v));
