// GENERATED by scripts/generate-stardust-ship-hull.mjs — do not edit by hand.
// Regenerate: node scripts/generate-stardust-ship-hull.mjs (after changing
// art/player-ship.png or drawCourier's size in gfx/stardustVfx.js).
//
// The player ship's collision hull: the outline of art/player-ship.png's
// opaque body (alpha > 40), simplified to 28 vertices (Douglas-Peucker,
// 18.35 px tolerance on the 1254 px sprite). Ship-local cells as drawn by
// drawCourier (a 1.056-cell square): x = right, y = forward (the
// nose), origin = sprite centre. Counter-clockwise, nose first. Concave.
// Measured opaque body: 0.869 wide x 0.953 long.
export const SHIP_HULL = Object.freeze([
  [-0.0051, 0.4960],
  [-0.1322, 0.1255],
  [-0.1996, 0.0143],
  [-0.4320, -0.2442],
  [-0.4337, -0.3234],
  [-0.4202, -0.3368],
  [-0.2796, -0.2964],
  [-0.2156, -0.3360],
  [-0.2173, -0.4017],
  [-0.1987, -0.3773],
  [-0.1827, -0.4413],
  [-0.1255, -0.4573],
  [-0.0716, -0.4135],
  [-0.0514, -0.3082],
  [-0.0227, -0.3545],
  [0.0211, -0.3554],
  [0.0497, -0.3074],
  [0.0724, -0.4152],
  [0.1432, -0.4573],
  [0.1827, -0.4421],
  [0.1987, -0.3764],
  [0.2156, -0.4059],
  [0.2156, -0.3360],
  [0.2796, -0.2964],
  [0.4303, -0.3318],
  [0.4337, -0.2535],
  [0.1356, 0.1187],
  [0.0328, 0.4463],
].map((v) => Object.freeze(v)));

/** The sprite's opaque body (alpha > 40) as measured when the hull was traced. */
export const SHIP_BODY = Object.freeze({ width: 0.8691, length: 0.9533, alphaThreshold: 40, spriteCells: 1.0560 });
